### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by zoeyfyi** [ZanderBrown/zanderbrown.github.io#1]
Just had a poke around, and noticed these 2 things:

- This Flatpak link is broken:
https://github.com/ZanderBrown/zanderbrown.github.io/blob/2911f592f4d4083b5d65b81241e7d7c5cfcd7206/index.html#L30
- This appears to link to the wrong project:
https://github.com/ZanderBrown/zanderbrown.github.io/blob/2911f592f4d4083b5d65b81241e7d7c5cfcd7206/index.html#L31

**Comment by ZanderBrown** [comment]
Thanks, to be completely honest I'd forgotten about that page :-)
